// Code generated by gen-keys - DO NOT EDIT.

package locales

// Used to index i18n values
type LK string

// Used to pipe key and arguments into ctxi18n
type LKMessage struct {
	Key  LK
	Args []any
}

const (
	LKAppTitle                    LK = "app.title"
	LKFormsEmailErrorGeneric      LK = "forms.email.error-generic"
	LKFormsEmailTitle             LK = "forms.email.title"
	LKFormsErrorAlreadyExists     LK = "forms.error.already-exists"
	LKFormsErrorInvalidCredential LK = "forms.error.invalid-credential"
	LKFormsPasswordConfirm        LK = "forms.password.confirm"
	LKFormsPasswordErrorCase      LK = "forms.password.error-case"
	LKFormsPasswordErrorLength    LK = "forms.password.error-length"
	LKFormsPasswordErrorMustMatch LK = "forms.password.error-must-match"
	LKFormsPasswordErrorSymbol    LK = "forms.password.error-symbol"
	LKFormsPasswordTitle          LK = "forms.password.title"
	LKFormsUsernameErrorLength    LK = "forms.username.error-length"
	LKFormsUsernameErrorSpaces    LK = "forms.username.error-spaces"
	LKFormsUsernameTitle          LK = "forms.username.title"
	LKLoginNoAccount              LK = "login.no-account"
	LKLoginRegister               LK = "login.register"
	LKLoginTitle                  LK = "login.title"
	LKNavbarHouses                LK = "navbar.houses"
	LKNavbarMessaging             LK = "navbar.messaging"
	LKNavbarNotes                 LK = "navbar.notes"
	LKNavbarPayments              LK = "navbar.payments"
	LKNavbarProfile               LK = "navbar.profile"
	LKRegisterAlreadyHaveAccount  LK = "register.already-have-account"
	LKRegisterTitle               LK = "register.title"
)
