// Code generated by gen-keys - DO NOT EDIT.

package locales

// Used to index i18n values
type LK string

// Used to pipe key and arguments into ctxi18n
type LKMessage struct {
	Key  LK
	Args []any
}

const (
	LKAppTitle                            LK = "app.title"
	LKFormsContentTitle                   LK = "forms.content.title"
	LKFormsDelete                         LK = "forms.delete"
	LKFormsEdit                           LK = "forms.edit"
	LKFormsEmailErrorGeneric              LK = "forms.email.error-generic"
	LKFormsEmailTitle                     LK = "forms.email.title"
	LKFormsErrorAlreadyExists             LK = "forms.error.already-exists"
	LKFormsErrorInvalidCredential         LK = "forms.error.invalid-credential"
	LKFormsErrorsNoMultipleSpaces         LK = "forms.errors.no-multiple-spaces"
	LKFormsErrorsOnlyLettersAndDigits     LK = "forms.errors.only-letters-and-digits"
	LKFormsFullNameInfo                   LK = "forms.full-name.info"
	LKFormsFullNameMarkPublic             LK = "forms.full-name.mark-public"
	LKFormsFullNameTitle                  LK = "forms.full-name.title"
	LKFormsHouseAddUsers                  LK = "forms.house.add-users"
	LKFormsHouseErrorSomeRoommatesInvalid LK = "forms.house.error-some-roommates-invalid"
	LKFormsHouseNameLabel                 LK = "forms.house.name-label"
	LKFormsHouseTitle                     LK = "forms.house.title"
	LKFormsHouseTitleNew                  LK = "forms.house.title-new"
	LKFormsNameErrorEmpty                 LK = "forms.name.error-empty"
	LKFormsNameTitle                      LK = "forms.name.title"
	LKFormsNoteTitle                      LK = "forms.note.title"
	LKFormsNoteTitleNew                   LK = "forms.note.title-new"
	LKFormsPasswordConfirm                LK = "forms.password.confirm"
	LKFormsPasswordErrorCase              LK = "forms.password.error-case"
	LKFormsPasswordErrorLength            LK = "forms.password.error-length"
	LKFormsPasswordErrorMustMatch         LK = "forms.password.error-must-match"
	LKFormsPasswordErrorSymbol            LK = "forms.password.error-symbol"
	LKFormsPasswordTitle                  LK = "forms.password.title"
	LKFormsSubmit                         LK = "forms.submit"
	LKFormsUpdate                         LK = "forms.update"
	LKFormsUsernameErrorLength            LK = "forms.username.error-length"
	LKFormsUsernameErrorSpaces            LK = "forms.username.error-spaces"
	LKFormsUsernameInfo                   LK = "forms.username.info"
	LKFormsUsernameTitle                  LK = "forms.username.title"
	LKHousesNoHouses                      LK = "houses.no-houses"
	LKHousesRoomateCount                  LK = "houses.roomate-count"
	LKHousesYourHouses                    LK = "houses.your-houses"
	LKLoginNoAccount                      LK = "login.no-account"
	LKLoginRegister                       LK = "login.register"
	LKLoginTitle                          LK = "login.title"
	LKNavbarHouses                        LK = "navbar.houses"
	LKNavbarMessaging                     LK = "navbar.messaging"
	LKNavbarNotes                         LK = "navbar.notes"
	LKNavbarPayments                      LK = "navbar.payments"
	LKNavbarProfile                       LK = "navbar.profile"
	LKRegisterAlreadyHaveAccount          LK = "register.already-have-account"
	LKRegisterTitle                       LK = "register.title"
	LKSearchResultsFor                    LK = "search-results-for"
)
