#:schema https://raw.githubusercontent.com/air-verse/air/0a3f56961f682c08c2d012dbf828188b4e12e854/air.schema.json
root = "."
tmp_dir = "tmp"

[build]
cmd = "sh build.sh"
# i hate that I spent time to find a workaround rather than going with something else
# https://github.com/air-verse/air/blob/a830e5a27ac354edcd6c6d190dd678a78bc06035/runner/util.go#L438
bin = "DNR.exe\"; sh \"air-bin.sh"

exclude_dir = ["assets", "tmp", "vendor", "testdata", "db\\dbqueries", "docs"]
exclude_file = ["locales\\locales-keys.go"]
exclude_regex = ["_test.go", "_templ.go"]
include_dir = []
include_file = ["air-bin.sh", "locales\\et\\et.yaml"]
include_ext = ["go", "tpl", "tmpl", "html", "templ"]

delay = 3000
rerun_delay = 1000
kill_delay = 500
send_interrupt = false
stop_on_error = false
log = "air.log"

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = true

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
